services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - skullnet

  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "9000:9000"
      #- "443:9000" # TODO - check how to https/ssl
    networks:
      - skullnet

# todo
#  redis:
#    image: redis

# todo
networks:
  skullnet:
    driver: host